import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Theme from '@/components/providers/Theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'THEKHTECH INC.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
        <Theme>
          <Navbar />
            <main className='container w-11/12 mx-auto'>
              {children}
            </main>
          <Footer />
        </Theme>
      </body>
    </html>
  )
}
